import random
from translate import translateGame

option = ""

while option != "x":
    print(" ")
    print("Harry Potter à l'école des sorciers")
    print("par J.K. Rowling")
    print(" ")
    print("Pour Jessica, qui adore les histoires,")
    print("pour Anne, qui les adorait aussi,")
    print("et pour Di, qui a été la première à entendre celle-ci.")
    print(" ")
    print("Liste des chapitres")
    print("Chapitre 1 : Le Survivant")
    print("Chapitre 2 : Une Vitre Disparaît")
    print("Chapitre 3 : Les Lettres de Nulle Part")
    print("Chapitre 4 : Le Gardien des Clés")
    print("Chapitre 5 : Le Chemin de Traverse")
    print("Chapitre 6 : Rendez – Vous sur la Voie 9 3/4")
    print("Chapitre 7 : Le Choixpeau Magique")
    print("Chapitre 8 : Le Maître des Potions")
    print("Chapitre 9 : Duel à Minuit")
    print("Chapitre 10 : Halloween")
    print("Chapitre 11 : Le Match de Quidditch")
    print("Chapitre 12 : Le Miroir de Riséd")
    print("Chapitre 13 : Nicolas Flamel")
    print("Chapitre 14 : Norbert le Dragon")
    print("Chapitre 15 : La Forêt Interdite")
    print("Chapitre 16 : Sous la Trappe")
    print("Chapitre 17 : L’ Homme aux Deux Visages")
    print(" ")
    option = input("Sélectionnez un chapitre ou sortir(X): ")

    option.lower()

    if option=="1":

        wordsChapitre1 = {
            "avoir": ("haber","tener"),
            "être" : "ser",
            "faire" : "hacer",
            "mots" : "palabras",
            "quiconque" : ("nadie","cualquiera","alguien"),
            "pendant" : "durante",
            "parfois" : "a veces",
            "blessé" : "herido",
            "presque" : "casi",
            "jusqu'a" : "hasta",
            "quelque chose" : "algo",
            "perceuses" : "taladros",
            "leurs" : "sus",
            "depuis" : "desde",
            "car" : "porque",
            "entendre" : "escuchar",
            "toutes deux" : "ambos",
            "chaise" : "silla",
            "jeter" : ("tirar","lanzar","echar","arrojar"),
            "assis" : "sentado",
            "tandis" : "mientras",
            "commande" : "pedido",
            "beignet" : ("rosquilla","dona"),
            "vers" : "hacia",
            "boutique" : "tienda",
            "avant" : "antes",
            "cet" : "este",
            "temps" : ("tiempo","clima"),
            "prochaine" : ("siguiente","próximo"),
            "sur" : ("en","sobre"),
            "loin" : "lejos",
            "robe" : ("vestido","tunica"),
            "emporter" : "llevar",
            "attendre" : "esperar",
            "baisser" : "beso",
            "cette" : "esta",
            "habitaient" : ("habitaban","vivían"),
            "avaient" : ("habían","tenían"),
            "toujours" : "siempre",
            "affirmé" : ("afirmado","asegurado"),
            "fierté" : "orgullo",
            "étaient": "eran",
            "aurait" : ("tendría","habría","hubiera"),
            "n'aurait" : ("no tendría","no habría","no hubiera"),
            "jamais" : ("jamas","nunca"),
            "puissent" : ("pueden","puede","poder","pueda"),
            "trouver" : "encontrar",
            "se trouver" : "encontrarse",
            "dans" : ("en","dentro","a","durante","a lo largo"),
            "quoi que ce soit" : "cualquier cosa",
            "n'avaient" : ("no tenían"),
            "sornettes" : ("tonterias","disparates"),
            "dirigeait" : "dirigía",
            "massif" : ("macizo","masivo","enorme"),
            "en revanche" : ("sin embargo","en cambio","por el contrario"),
            "n'avait" : "no tenía",
            "belle taille" : "buen tamaño",
            "quant à elle" : "en cuanto a ella",
            "était" : "era",
            "mince" : "delgada",
            "fort utile" : "muy útil",
            "en regardant" : "mirando",
            "par-dessus" : ("por arriba","encima","arriba"),
            "clôtures" : ("cercas","vallas"),
            "bel" : ("hermoso","bello"),
            "vouloir" : "querer",
            "voulaient" : ("querían","deseaban"),
            "dont" : ("el cual","cuyo"),
            "craignaient" : "temían",
            "qu'ils" : "que ellos",
            "si jamais" : "si alguna vez",
            "venait" : "venía",
            "convaincus" : "convencidos",
            #"qu'ils ne s'en remettraient pas" : "que no se recuperarían",
            "sœur" : "hermana",
            "frère" : "hermano",
            #"ne s'etaient plus revues" : "no se habían vuelto a ver",
            "années" : "años",
            "En fait" : "de hecho",
            "faisait" : "hacía",
            "fille" : ("hija","chica","muchacha","niña"),
            "fils" : ("niño","chico","muchacho","hijo"),
            "bon à rien" : "bueno para nada",
            "mari" : ("marido","esposo"),
            "aussi" : "también",
            "éloignés" : ("distante","lejano","remoto"),
            #"aussi éloignés que possible" : ("tan lejanos como sea posible","tan lejos como sea posible","tan distantes entre sí como sea posible"),
            #"de tout ce qui faisait" : "de todo lo que hacía",
            "qui" : ("que","quien"),
            "tremblaient" : "temblaban",
            "épouvante" : ("horror","terror"),
            "par malheur" : "por desgracia",
            "diraient" : "dirían",
            "montraient" : "mostraban",
            "leur" : "su",
            "rue" : "calle",
            "savaient" : "sabían",
            "eux aussi" : "también",
            "garçon" : ("niño","chico","joven"),
            "vu" : "visto",
            "supplémentaire" : ("suplementario","adicional"),
            "de tenir" : "de tener",
            #"n'était pas question" : "estaba fuera de cuestión",
            "se mette" : ("se ponga","ponerse"),
            "mette" : ("poner","colocar","dejar"),
            "celui-là" : ("ese","aquel"),
            "lorsque" : "cuando",
            "s'éveillèrent" : "se despertaron",
            "il faisait" : "era",
            "nuageux" : "nublado",
            #"ne laissait prévoir" : "no dejaba predecir",
            "allaient" : "iban",
            "bientôt" : "pronto",
            "fredonnait un air" : "tarareaba una melodía",
            "en nouant" : "atando",
            "cravate" : "corbata",
            "aller" : ("ir","vamos","andar"),
            "travailler" : "trabajar",
            "racontait" : ("estaba contando","estaba diciendo"),
            "un ton badin" : "un tono juguetón",
            "dernier" : "último",
            "potins" : "chismes",
            "quartier" : "barrio",
            #"en s'efforçant" : "esforzándose",
            "jeune" : "joven",
            "mardi" : "martes",
            "jaune" : "amarillo",
            "braillat" : "gritaba",
            "aucun" : ("ninguno","no"),
            "eux" : "ellos",
            "remarqua" : ("notó","notado"),
            "grosse" : ("grande","gran"),
            "au" : ("a","en","de"),
            "chouette" : ("búho", "lechuza"),
            "plumage mordoré" : ("plumaje bronce","plumaje marrón dorado","plumaje café dorado"),
            "devant" : ("delante","frente"),
            "voleta" : "revoloteó",
            "fenêtre" : "ventana",
            "à" : ("a las", "a","en","por","para"),
            "demie" : ("medio","mitad"),
            "huit heures et demie" : ("ocho y media","ocho horas y media"),
            "prit" : "tomó",
            "attaché-case" : "maletín",
            "déposa" : ("dejó","depositó"),
            "joue" : ("mejilla","jugar","juego"),
            "essaya" : ("trató","intentó"),
            "embrasser" : ("besar","abrazar"),
            "mais" : ("pero","sino"),
            "sans" : "sin",
            "celui-ci" : ("ese"),
            "proie" : ("víctima","presa"),
            "s'appliquait" : "se puso",
            "pièce" : "habitación",
            "assiette" : "plato",
            "gloussa" : "se rio entre dientes",
            "quittant" : "dejando",
            "maison" : "casa",
            "monta" : "subió",
            "voiture" : "carro",
            "sa" : "su",
            "recula" : "retrocedió",
            #"le long de l'allée" : "a lo largo del camino",
            "menait" : ("que conduce","conducía","conduce"),
            "Ce fut" : ("fue","esto fue"),
            "coin de la rue" : "esquina de la calle",
            "fois" : "vez",
            "lisait" : "leía",
            "carte routière" : "mapa de carretera",
            "comprit" : ("comprendió","entendido","comprendido"),
            "ne comprit pas" : ("no comprendió","no entendía"),
            "très bien" : "muy bien",
            "voir" : "ver",
            "venait de voir" : "acababa de ver",
            "tourna" : ("giró","volteó"),
            "alors" : "entonces",
            "tête" : "cabeza",
            "regarder" : "mirar",
            "tigré" : "atigrado",
            "coin" : "esquina",
            "moindre trace" : "menor rastro",
            "qu'est-ce qui" :  "que",
            "passer" : "pasado",
            "avait" : ("tenía","había"),
            #"il avait dû" : ("el tenía que","el tuvo que"),
            #"se laisser abuser" : "dejado engañar",
            "reflet" : "reflejo",
            "soleil" : "sol",
            "trottoir" : ("acera","pavimento"),















        }

        sentencesChapitre1 = {
            "avoir": "J'aimerais avoir 20 dollars.",
            "être" : "Vous devez être plus clairs.",
            "faire" : "Faire la cuisine",
            "mots" : "Mais les mots ne suffisent plus.",
            "quiconque" : "Jamais quiconque n'aurait imaginé...",
            "pendant" : "et que pendant des semaines, il serait...",
            "parfois" : "les jeunes avaient parfois de ces accoutrements",
            "blessé" : "Hagrid laissa échapper un long hurlement de chien blessé",
            "presque" : " saisit son téléphone et avait presque fini de composer le numéro de sa maison ",
            "jusqu'a" : " et de sa barbe qui lui descendaient jusqu'à la taille.",
            "quelque chose" : " Il était occupé à chercher quelque chose dans sa longue cape",
            "perceuses" : "une enterprise qui fabriquait des perceuses",
            "leurs" : "et c'était à leurs yeux",
            "depuis" : "mais toutes deux ne s'étaient plus revues depuis des années.",
            "car" : "",
            "entendre" : "escuchar",
            "toutes deux" : "ambos",
            "chaise" : "silla",
            "jeter" : ("tirar","lanzar","echar","arrojar"),
            "assis" : "sentado",
            "tandis" : "mientras",
            "commande" : "pedido",
            "beignet" : ("rosquilla","dona"),
            "vers" : "hacia",
            "boutique" : "tienda",
            "avant" : "antes",
            "cet" : "este",
            "temps" : ("tiempo","clima"),
            "prochaine" : ("siguiente","próximo"),
            "sur" : ("en","sobre"),
            "loin" : "lejos",
            "robe" : ("vestido","tunica"),
            "emporter" : "llevar",
            "attendre" : "esperar",
            "baisser" : "beso",
            "cette" : "esta",
            "habitaient" : ("habitaban","vivían"),
            "avaient" : ("habían","tenían"),
            "toujours" : "siempre",
            "affirmé" : ("afirmado","asegurado"),
            "fierté" : "orgullo",
            "étaient": "eran",
            "aurait" : ("tendría","habría","hubiera"),
            "n'aurait" : ("no tendría","no habría","no hubiera"),
            "jamais" : ("jamas","nunca"),
            "puissent" : ("pueden","puede","poder","pueda"),
            "trouver" : "encontrar",
            "se trouver" : "encontrarse",
            "dans" : ("en","dentro","a","durante","a lo largo"),
            "quoi que ce soit" : "cualquier cosa",
            "n'avaient" : ("no tenían"),
            "sornettes" : ("tonterias","disparates"),
            "dirigeait" : "dirigía",
            "massif" : ("macizo","masivo","enorme"),
            "en revanche" : ("sin embargo","en cambio","por el contrario"),
            "n'avait" : "no tenía",
            "belle taille" : "buen tamaño",
            "quant à elle" : "en cuanto a ella",
            "était" : "era",
            "mince" : "delgada",
            "fort utile" : "muy útil",
            "en regardant" : "mirando",
            "par-dessus" : ("por arriba","encima","arriba"),
            "clôtures" : ("cercas","vallas"),
            "bel" : ("hermoso","bello"),
            "vouloir" : "querer",
            "voulaient" : ("querían","deseaban"),
            "dont" : ("el cual","cuyo"),
            "craignaient" : "temían",
            "qu'ils" : "que ellos",
            "si jamais" : "si alguna vez",
            "venait" : "venía",
            "convaincus" : "convencidos",
            "qu'ils ne s'en remettraient pas" : "que no se recuperarían",
            "sœur" : "hermana",
            "frère" : "hermano",
            "ne s'etaient plus revues" : "no se habían vuelto a ver",
            "années" : "años",
            "En fait" : "de hecho",
            "faisait" : "hacía",
            "fille" : ("hija","chica","muchacha","niña"),
            "fils" : ("niño","chico","muchacho","hijo"),
            "bon à rien" : "bueno para nada",
            "mari" : ("marido","esposo"),
            "aussi" : "también",
            "éloignés" : ("distante","lejano","remoto"),
            "aussi éloignés que possible" : ("tan lejanos como sea posible","tan lejos como sea posible","tan distantes entre sí como sea posible"),
            "de tout ce qui faisait" : "de todo lo que hacía",
            "qui" : ("que","quien"),
            "tremblaient" : "temblaban",
            "épouvante" : ("horror","terror"),
            "par malheur" : "por desgracia",
            "diraient" : "dirían",
            "montraient" : "mostraban",
            "leur" : "su",
            "rue" : "calle",
            "savaient" : "sabían",
            "eux aussi" : "también",
            "garçon" : ("niño","chico","joven"),
            "vu" : "visto",
            "supplémentaire" : ("suplementario","adicional"),
            "de tenir" : "de tener",
            "n'était pas question" : "estaba fuera de cuestión",
            "se mette" : ("se ponga","ponerse"),
            "mette" : ("poner","colocar","dejar"),
            "celui-là" : ("ese","aquel"),
            "lorsque" : "cuando",
            "s'éveillèrent" : "se despertaron",
            "il faisait" : "era",
            "nuageux" : "nublado",
            "ne laissait prévoir" : "no dejaba predecir",
            "allaient" : "iban",
            "bientôt" : "pronto",
            "fredonnait un air" : "tarareaba una melodía",
            "en nouant" : "atando",
            "cravate" : "corbata",
            "aller" : ("ir","vamos","andar"),
            "travailler" : "trabajar",
            "racontait" : ("estaba contando","estaba diciendo"),
            "un ton badin" : "un tono juguetón",
            "dernier" : "último",
            "potins" : "chismes",
            "quartier" : "barrio",
            "en s'efforçant" : "esforzándose",
            "jeune" : "joven",
            "mardi" : "martes",
            "jaune" : "amarillo",
            "braillat" : "gritaba"
        }

        translateGame(wordsChapitre1)
